Video.create(title: "A sweet video 1", description: "https://www.youtube.com/embed/FcnhekTNHPg")
Video.create(title: "A sweet video 2", description: "https://www.youtube.com/embed/AxM9FYSs8V4")
Video.create(title: "A sweet video 3", description: "https://www.youtube.com/embed/5iV_hB08Uns")
Video.create(title: "A sweet video 4", description: "https://www.youtube.com/embed/t0_JMBPOdLw")
Video.create(title: "A sweet video 5", description: "https://www.youtube.com/embed/xIqza5kdmdQ")