Video.create(description: "https://www.youtube.com/embed/FcnhekTNHPg")
Video.create(description: "https://www.youtube.com/embed/AxM9FYSs8V4")
Video.create(description: "https://www.youtube.com/embed/5iV_hB08Uns")
Video.create(description: "https://www.youtube.com/embed/t0_JMBPOdLw")
Video.create(description: "https://www.youtube.com/embed/xIqza5kdmdQ")